---
kind: pipeline
type: docker
name: verify-pr
steps:
  - name: install
    image: danlynn/ember-cli:3.28.5
    commands:
      - npm install
  - name: lint
    image: danlynn/ember-cli:3.28.5
    commands:
      - npm run lint
  - name: test
    image: danlynn/ember-cli:3.28.5
    commands:
      - npm run test:ember
trigger:
  event:
    - pull_request
---
kind: pipeline
type: docker
name: verify-build
steps:
  - name: build-dry-run
    image: plugins/docker
    settings:
      repo: lblod/frontend-worship-decisions
      dry_run: true
      purge: true
trigger:
  event:
    - pull_request
---
kind: pipeline
type: docker
name: push-latest-build
steps:
  - name: push-latest-build
    image: plugins/docker
    settings:
      repo: lblod/frontend-worship-decisions
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      purge: true
trigger:
  branch:
    - development
  event:
    exclude:
      - pull_request
---
kind: pipeline
type: docker
name: release
steps:
  - name: push-tagged-build
    image: plugins/docker
    settings:
      repo: lblod/frontend-worship-decisions
      tags: ${DRONE_TAG##v}
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      purge: true
trigger:
  event:
    - tag
---
kind: secret
name: docker_username
---
kind: secret
name: docker_password
---
kind: signature
