---
kind: pipeline
type: docker
name: verify-pr
steps:
- name: install
  image: danlynn/ember-cli:3.20.0
  commands:
  - npm install
- name: lint
  image: danlynn/ember-cli:3.20.0
  commands:
  - npm run lint
- name: test
  image: danlynn/ember-cli:3.20.0
  commands:
  - npm run test:ember
trigger:
  event:
    - pull_request
---
kind: pipeline
type: docker
name: verify-build
steps:
- name: build-dry-run
  image: plugins/docker
  settings:
    repo: lblod/frontend-public-decisions
    dry_run: true
    purge: true
---
kind: pipeline
type: docker
name: push-latest-build
steps:
- name: push-latest-build
  image: plugins/docker
  settings:
    repo: lblod/frontend-public-decisions
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    purge: true
trigger:
  branch:
    - development
  event:
    exclude:
    - pull_request
---
kind: pipeline
type: docker
name: release
steps:
- name: push-tagged-build
  image: plugins/docker
  settings:
    repo: lblod/frontend-public-decisions
    tags: ${DRONE_TAG##v}
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    purge: true
trigger:
  event:
    - tag
---
kind: secret
name: docker_username
data: xZslq485H302HoIP3MHO1mW9Mc7xDikPgXBkSGH/pFTMYxAgbAAmdA==
---
kind: secret
name: docker_password
data: KuzOThczhYWILRiJlyR/8jNcDhx1FpOgkRRwiDixqlC93X8PT2Eihto+zufbc85Uc0vG3yIRgKxEzZtAH1GSKg==
---
kind: signature
hmac: 1ae34e51bc3a85b9d894716aab66750fa2664033e841955802b84187737b89b6

...
