pipeline:
  install:
    image: madnificent/ember:4.12.1
    commands:
      - npm install
  lint:
    image: madnificent/ember:4.12.1
    commands:
      - npm run lint
  test:
    image: madnificent/ember:4.12.1
    commands:
      - npm run test:ember
when:
  event: pull_request
