pipeline:
  install:
    image: danlynn/ember-cli:5.3.0-node_18.18
    commands:
      - npm install
  lint:
    image: danlynn/ember-cli:5.3.0-node_18.18
    commands:
      - npm run lint
  test:
    image: danlynn/ember-cli:5.3.0-node_18.18
    commands:
      - npm run test:ember
when:
  event: pull_request
